---
title: "Figure 2"
author: "Meiling Zhang"
date: "2022/3/5"
output: html_document
---


# Figure 2a

```{r data, warning=FALSE}
library(ggplot2)
library(ggpubr)

#data
data = read.table("Cumulative_UP.csv",header = T, row.names=1,sep = ",")
Field=factor(data$Fieldtype,levels = c("Upland","Paddy"))

group="Cumulative_UP"
p0 <- ggplot(data, aes(x=Field, y=Values,color=Field)) + geom_boxplot(width=0.5,outlier.size = 0.2)+
  theme(panel.background = element_rect(colour = "black"))+theme_bw()+theme(legend.title=element_text(size=7),legend.text=element_text(size=7))+
  theme(legend.position='right',legend.key.size = unit(0.3,'cm'))+
  theme(panel.grid.major =  element_line(size=0.1),panel.grid.minor = element_line(size = 0.1))+
  theme(axis.title.y= element_text(size=10))+theme(axis.title.x = element_text(size = 10))+
  theme(axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7))+
  xlab(paste0(group))+ ylab(expression(paste("CO"["2"], " flux", " (mg"," C"," kg"^"-1","soil)"),color="black"))+facet_wrap( ~ Group, scales="free", ncol=4)+theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())
p0
p <- p0+geom_jitter(width = 0.2,aes(color=Field),size=0.6,alpha=0.5)+
  scale_fill_manual(values=c("white", "white"))+
  scale_color_manual(values=c("#F46D43","#3288BD"))+stat_compare_means(method="wilcox.test")
p

width=180
height = 70
ggsave(paste0("",group,".pdf"), p, width = width, height = height, units = "mm")
ggsave(paste0("",group,".JPEG"), p, width = width, height = height, units = "mm")
```

# Figure 2b

```{r, data}
library(ggplot2)
library(ggpubr)
data = read.csv("Cumulative_latitude_PE.csv",header = T,row.names=1,sep = ",")

Treat=factor(data$Treatment,levels = c("UplandPE","PaddyPE"))
group="Cumulative_latitude_PE"
p=ggplot(data, aes(x = Latitude, y = Values_day60,color=Treat)) +
geom_point(aes(color=Treat),size=2,alpha=0.6) +
geom_smooth(aes(color=Treat),method="lm",size=0.5) +
labs(title = '',x = 'Latitude', y = 'Priming effect')+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  ggpubr::stat_cor(method = "pearson")+scale_color_manual(values=c("#F46D43","#3288BD"))
p

width = 120
height = 90
ggsave(paste0("",group,".JPEG"), p, width = width, height = height, units = "mm")
ggsave(paste0("",group,".pdf"), p, width = width, height = height, units = "mm")
```

## Figure 2c-d

```{r, data}
library(ggplot2)
library(ggpubr)

data = read.csv("Cumulative_pairs.csv",header = T,row.names=1,sep = ",")

group="Cumulative_pairs"
data$Fieldtype<-factor(data$Fieldtype,levels=c("Upland", "Paddy"), labels = c("Upland", "Paddy"))

p=ggplot(data, aes(x = PE, y = Straw_BR,color=Group)) +
geom_point(aes(color=Group),size=2,alpha=0.6) +
geom_smooth(color="black",method="lm",size=0.5) +
labs(title = '',x = 'Latitude', y = 'Env')+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  ggpubr::stat_cor(method = "pearson")+scale_color_manual(values=c("#3288BD","#3288BD","#F46D43","#F46D43"))+
  facet_wrap( ~ Fieldtype+Pairs, scales="free", ncol=4,nrow=1)
p

width = 350
height = 90
ggsave(paste0("",group,".JPEG"), p, width = width, height = height, units = "mm")
ggsave(paste0("",group,".pdf"), p, width = width, height = height, units = "mm")
```








