---
title: "Figure 3"
author: "Meiling Zhang"
date: "2022/3/5"
output: html_document
---

# Figure 3a

```{r data, warning=FALSE}
library(ggplot2)
library(cowplot)

#All
factor<-read.csv("RF/importance_otu.scale_All.csv",header = T,row.names=1,sep = ",")
group="All"

variable=factor(factor$factor,levels = c("Field","Longitude","Latitude","Altitude","BR","F_Shannon","F_Faith_pd","F_Richness","F_Evenness","F_PCoA1","F_PCoA2","B_Shannon","B_Faith_pd","B_Richness","B_Evenness","B_PCoA1","B_PCoA2","MAP","MAT","pH","AP","AK","TN","TP","TK","OM","NH_N","NO_N"))
Treat=factor(factor$Class,levels=c("Field","Space","Microbial_activity","F_alpha","F_beta","B_alpha","B_beta","Climate","Soil"))

all <- ggplot() +
geom_col(data = factor, aes(x = variable, y = IncMSE,fill=Treat)) +
labs(title = NULL, x = NULL, y = 'Increase in MSE (%)', fill = NULL)+theme_bw() +
theme(panel.grid = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = 'black')) +
scale_y_continuous(expand = c(0, 0), limit = c(-3, 50)) +
geom_text(data = factor, aes(x = variable, y = IncMSE, label = IncMSE.sig), nudge_y = 5)+
annotate('text', label = sprintf('italic(R^2) == %.2f', 0.5193), x = 3, y = 30, size = 5, parse = TRUE)+coord_flip()+
scale_fill_manual(values=c("#000000","#543005","#A4772B","#E4AB23","#65A644","#D66127","#E52A8A","#7670B3","#199D77"))
all

#Upland
factor<-read.csv("RF/importance_otu.scale_Upland.csv",header = T,row.names=1,sep = ",")
group="Upland"

variable=factor(factor$factor,levels = c("Field","Longitude","Latitude","Altitude","BR","F_Shannon","F_Faith_pd","F_Richness","F_Evenness","F_PCoA1","F_PCoA2","B_Shannon","B_Faith_pd","B_Richness","B_Evenness","B_PCoA1","B_PCoA2","MAP","MAT","pH","AP","AK","TN","TP","TK","OM","NH_N","NO_N"))
Treat=factor(factor$Class,levels=c("Field","Space","Microbial_activity","F_alpha","F_beta","B_alpha","B_beta","Climate","Soil"))

upland <- ggplot() +
geom_col(data = factor, aes(x = variable, y = IncMSE,fill=Treat)) +
labs(title = NULL, x = NULL, y = 'Increase in MSE (%)', fill = NULL)+theme_bw() +
theme(panel.grid = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = 'black')) +
scale_y_continuous(expand = c(0, 0), limit = c(-3, 30)) +
geom_text(data = factor, aes(x = variable, y = IncMSE, label = IncMSE.sig), nudge_y = 5)+
annotate('text', label = sprintf('italic(R^2) == %.2f', 0.5190), x = 3, y = 20, size = 5, parse = TRUE)+coord_flip()+
scale_fill_manual(values=c("#000000","#543005","#A4772B","#E4AB23","#65A644","#D66127","#E52A8A","#7670B3","#199D77"))
upland

#Paddy
factor<-read.csv("RF/importance_otu.scale_Paddy.csv",header = T,row.names=1,sep = ",")
group="Paddy"

variable=factor(factor$factor,levels = c("Field","Longitude","Latitude","Altitude","BR","F_Shannon","F_Faith_pd","F_Richness","F_Evenness","F_PCoA1","F_PCoA2","B_Shannon","B_Faith_pd","B_Richness","B_Evenness","B_PCoA1","B_PCoA2","MAP","MAT","pH","AP","AK","TN","TP","TK","OM","NH_N","NO_N"))
Treat=factor(factor$Class,levels=c("Field","Space","Microbial_activity","F_alpha","F_beta","B_alpha","B_beta","Climate","Soil"))

paddy <- ggplot() +
geom_col(data = factor, aes(x = variable, y = IncMSE,fill=Treat)) +
labs(title = NULL, x = NULL, y = 'Increase in MSE (%)', fill = NULL)+theme_bw() +
theme(panel.grid = element_blank(), panel.background = element_blank(), axis.line = element_line(colour = 'black')) +
scale_y_continuous(expand = c(0, 0), limit = c(-3, 30)) +
geom_text(data = factor, aes(x = variable, y = IncMSE, label = IncMSE.sig), nudge_y = 5)+
annotate('text', label = sprintf('italic(R^2) == %.2f', 0.2907), x = 3, y = 20, size = 5, parse = TRUE)+coord_flip()+
scale_fill_manual(values=c("#000000","#543005","#A4772B","#E4AB23","#65A644","#D66127","#E52A8A","#7670B3","#199D77"))
paddy

all_plot <- plot_grid(all,upland,paddy,ncol = 3,nrow=1,align ="v")
all_plot

group="RF_MSE"
width = 500
height =240
ggsave(paste0("",group,".pdf"), all_plot, width = width, height = height,units = "mm")
ggsave(paste0("",group,".JPEG"), all_plot, width = width, height = height,units = "mm")
```

# Figure 3b

```{r}
library(ggplot2)
data = read.csv("RF/relation.csv",header = T,row.names=1,sep = ",")
data$Field=factor(data$Field,levels = c("Upland","Paddy"))

group="PE_factor"
p=ggplot(data, aes(x = Value, y = PE,color=Field)) +
geom_point(aes(color=Field),size=1.5,alpha=0.6) +
geom_smooth(color="black",method="lm",size=0.5) +
labs(title = '',x = 'Env', y = 'PE')+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  ggpubr::stat_cor(method = "spearman")+
  facet_wrap( ~ Factor, scales="free", ncol=2,nrow=2)+scale_color_manual(values=c("#F46D43","#3288BD"))
p

width = 150
height =120
ggsave(paste0("",group,".pdf"), p, width = width, height = height,units = "mm")
ggsave(paste0("",group,".JPEG"), p, width = width, height = height,units = "mm")
```

# Figure 3c

```{r package, include=FALSE}
#version =4.1.3
# if (!requireNamespace("devtools"))
# install.packages("devtools")
# install_github("gastonstat/plspm")
library(plspm)

#-----select factors-----#
sem<-read.csv("SEM/env_PE.csv",header = T,row.names=1,sep = ",")
attach(sem)

sem
Spatial <- c(0,0,0,0,0,0,0,0,0,0)
Field <- c(0,0,0,0,0,0,0,0,0,0)
Climate <- c(1,0,0,0,0,0,0,0,0,0)
Soil <- c(1,1,0,0,0,0,0,0,0,0)
B_alpha<- c(1,1,1,1,0,0,0,0,0,0)
B_beta<- c(1,1,1,1,0,0,0,0,0,0)
F_alpha<- c(1,1,1,1,0,0,0,0,0,0)
F_beta<- c(1,1,1,1,0,0,0,0,0,0)
BR<- c(1,1,1,1,0,0,0,0,0,0)
PE<- c(1,1,0,1,1,1,1,1,1,0)

sem_path=rbind(Spatial,Field,Climate,Soil,B_alpha,B_beta,F_alpha,F_beta,BR,PE)
innerplot(sem_path) 
colnames(sem_path) = rownames(sem_path)

sem_blocks <- list(					
  Spatial = c('Longitude','Latitude','Altitude'),					
  Field = 'Field',					
  Climate = c('MAP', 'MAT'), 					
  Soil = c('pH','AP','AK','TP','TK','NH_N','NO_N','OM','TN'),	
  B_alpha = c('B_Shannon','B_Evenness','B_Richness','B_Faith_pd'),
  B_beta = c('B_PCoA1','B_PCoA2'),
  F_alpha = c('F_Shannon','F_Evenness','F_Richness','F_Faith_pd'),
  F_beta = c('F_PCoA1','F_PCoA2'),
  BR = c('BR'),
  PE = 'PE')					
sem_modes = rep("A",10) 	
sem_pls = plspm(sem,sem_path,sem_blocks,modes = sem_modes,boot.val = T,br=1000)					
sem_pls						

sem_pls$gof 
x=sem_pls$outer_model
write.csv(x,file="loading.csv")


#-----select factors with loading value > 0.65-----#
sem<-read.csv("SEM/env_PE.csv",header = T,row.names=1,sep = ",")
attach(sem)

sem
Spatial <- c(0,0,0,0,0,0,0,0,0,0)
Field <- c(0,0,0,0,0,0,0,0,0,0)
Climate <- c(1,0,0,0,0,0,0,0,0,0)
Soil <- c(1,1,0,0,0,0,0,0,0,0)
B_alpha<- c(1,1,1,1,0,0,0,0,0,0)
B_beta<- c(1,1,1,1,0,0,0,0,0,0)
F_alpha<- c(1,1,1,1,0,0,0,0,0,0)
F_beta<- c(1,1,1,1,0,0,0,0,0,0)
BR<- c(1,1,1,1,0,0,0,0,0,0)
PE<- c(1,1,0,1,1,1,1,1,1,0)

sem_path=rbind(Spatial,Field,Climate,Soil,B_alpha,B_beta,F_alpha,F_beta,BR,PE)
innerplot(sem_path) 
colnames(sem_path) = rownames(sem_path)

sem_blocks <- list(					
  Spatial = c('Longitude','Latitude'),					
  Field = 'Field',					
  Climate = c('MAP', 'MAT'), 					
  Soil = c('pH', 'OM'),	
  B_alpha = c('B_Shannon','B_Evenness','B_Richness','B_Faith_pd'),
  B_beta = c('B_PCoA1'),
  F_alpha = c('F_Shannon','F_Evenness','F_Richness','F_Faith_pd'),
  F_beta = c('F_PCoA1'),
  BR = 'BR',
  PE = 'PE')					
sem_modes = rep("A",10) 	
sem_pls = plspm(sem,sem_path,sem_blocks,modes = sem_modes,boot.val = T,br=1000)					
sem_pls						

sem_pls$gof

group="path_coefs"
coefs=as.data.frame(sem_pls$path_coefs)
write.csv(coefs,file=paste0("",group,".csv"))

group="sig_values"
sem_pls$inner_model#copy

#effect
x=sem_pls$effects
write.csv(x,file="effect.csv")
```

# Figure 3d

```{r}
data<-read.csv("SEM/SEM_effect.csv",header = T,row.names=1,sep = ",")

library(ggplot2)
group="SEM effect"
data$Group=factor(data$Group,levels = c("Total","Direct","Indirect"))

p=ggplot(data,aes(x=Effect, y=Variable, fill=Group)) +
  geom_bar(stat="identity", position=position_dodge(0.9),width = 0.8) +
  theme_minimal()+ggtitle(paste0("",group))+
  ylab("Standardized effects")+theme_bw()+ theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  scale_fill_manual(values=c("#00C2A5", "#FF8D5E","#85A0CE"))+ expand_limits(x=c(-0.6,0.3))+scale_y_discrete(limits=c("B_beta","B_alpha","F_beta","F_alpha","BR","Soil","Climate","Field","Space"))
  p

width =70
height = 60
ggsave(paste0("",group,".JPEG"), p, width = width, height = height, units = "mm")
ggsave(paste0("",group,".pdf"), p, width = width, height = height, units = "mm")
```

