---
title: "Figure 1"
author: "Meiling Zhang"
date: "2022/3/5"
output: html_document
---

# Figure 1c

```{r}
library(ggplot2)
library(ggpubr)

#data
points = read.csv("env/env.csv",header = T,row.names=1,sep = ",")

group="sig"
sub_points = subset(points,points$Factor%in% c("AK","NH_N","OM","pH","TK","TN","MAT","MAP"))
sub_points$FieldType=factor(sub_points$FieldType,levels = c("Upland","Paddy"),labels = c("Upland","Paddy"))
sub_points$Factor=factor(sub_points$Factor,levels = c("AK","NH_N","OM","pH","TK","TN","MAT","MAP"),labels = c("AK","NH_N","OM","pH","TK","TN","MAT","MAP"))

sig=ggplot(sub_points, aes(x = Latitude, y = Env,color=FieldType)) +
  geom_point(aes(color=FieldType),alpha = 1, size = 3,shape = 21) +
  geom_smooth(color="black",method="lm",size=0.5) +
  labs(title = '',x = 'Latitude', y = 'Env')+
  theme_bw()+
  theme(panel.grid.major=element_blank(),panel.grid.minor=element_blank())+
  ggpubr::stat_cor(method = "pearson")+scale_color_manual(values=c("#F46D43","#3288BD"))+facet_wrap( ~ Factor, scales="free", ncol=2,nrow=4)
sig

group="sig"
width = 180
height =300
ggsave(paste0("",group,".JPEG"), sig, width = width, height = height, units = "mm")
ggsave(paste0("",group,".pdf"), sig, width = width, height = height, units = "mm")
```

# Figure 1d

```{r setup, include=FALSE}
Env = read.table("mantel/env.csv",header = T, row.names=1,sep = ",")
otu_b = read.table("mantel/otutab_b.txt", header=T, row.names=1, sep="\t", comment.char="")
otu_F = read.table("mantel/otutab_F.txt", header=T, row.names=1, sep="\t", comment.char="")
sub_otu_B=otu_b[,row.names(Env)]
sub_otu_F=otu_F[,row.names(Env)]
norm_b=as.data.frame(t(t(sub_otu_B)/colSums(sub_otu_B,na=T))*100)
norm_f=as.data.frame(t(t(sub_otu_F)/colSums(sub_otu_F,na=T))*100)
remove_norm_b=as.data.frame(norm_b[rowSums(norm_b)>0,])
remove_norm_f=as.data.frame(norm_f[rowSums(norm_f)>0,])
norm_B=as.data.frame(t(remove_norm_b))
colnames(norm_B) <- paste("B", colnames(norm_B), sep = "_")
norm_F=as.data.frame(t(remove_norm_f))
colnames(norm_F) <- paste("F", colnames(norm_F), sep = "_")
write.csv(norm_B,file="norm_B.csv")
write.csv(norm_F,file="norm_F.csv")

#ggcor
#dnowload: https://github.com/mj163163/ggcor-1 (put the ggcor packages in library)
#devtools::install_local("C:/Users/BRAVEGIRL/Documents/R/win-library/4.0/ggcor_master.zip")
library(ggcor)
library(ggplot2)
library(dplyr)
library(cowplot)

#data
env = read.table("mantel/env.csv",header = T, row.names=1,sep = ",")
norm_B = read.table("mantel/norm_B.csv",header = T, row.names=1,sep = ",")
norm_F = read.table("mantel/norm_F.csv",header = T, row.names=1,sep = ",")
norm=cbind(norm_B,norm_F)
design = read.table("mantel/metadata.csv",header = T, row.names=1,sep = ",")

#upland
subdesign=subset(design, design$FieldType%in% c("Upland"))
sub_env=env[row.names(subdesign),]
sub_norm=norm[row.names(subdesign),]

set_scale()
quickcor(mtcars) + geom_square()
quickcor(mtcars, type = "upper") + geom_circle2()
quickcor(mtcars, cor.test = TRUE) +
  geom_square(data = get_data(type = "lower", show.diag = FALSE)) +
  geom_mark(data = get_data(type = "upper", show.diag = FALSE), size = 2.5) +
  geom_abline(slope = -1, intercept = 12)

mantel <- mantel_test(sub_norm, sub_env,spec.dist.method = 'bray', env.dist.method = 'euclidean',
                      spec.select = list(Bacterial_communities = 1:42183,
                                         Fungal_communities = 42184:60783)) %>% 
  mutate(rd = cut(r, breaks = c(-Inf, 0.2, 0.4, Inf),
                  labels = c("< 0.2", "0.2 - 0.4", ">= 0.4")),
         pd = cut(p.value, breaks = c(-Inf, 0.01, 0.05, Inf),
                  labels = c("< 0.01", "0.01 - 0.05", ">= 0.05")))

p1=quickcor(sub_env, type = "upper") +
  geom_square() +
  anno_link(aes(colour = pd, size = rd), data = mantel) +
  scale_size_manual(values = c(0.5, 1, 2)) +
  scale_colour_manual(values = c("#D95F02", "#1B9E77", "#A2A2A288")) +
  guides(size = guide_legend(title = "Mantel's r",
                             override.aes = list(colour = "grey35"), 
                             order = 2),
         colour = guide_legend(title = "Mantel's p", 
                               override.aes = list(size = 3), 
                               order = 1),
         fill = guide_colorbar(title = "Pearson's r", order = 3))

p1

#paddy
subdesign=subset(design, design$FieldType%in% c("Paddy"))
sub_env=env[row.names(subdesign),]
sub_norm=norm[row.names(subdesign),]

set_scale()
quickcor(mtcars) + geom_square()
quickcor(mtcars, type = "upper") + geom_circle2()
quickcor(mtcars, cor.test = TRUE) +
  geom_square(data = get_data(type = "lower", show.diag = FALSE)) +
  geom_mark(data = get_data(type = "upper", show.diag = FALSE), size = 2.5) +
  geom_abline(slope = -1, intercept = 12)

mantel <- mantel_test(sub_norm, sub_env,spec.dist.method = 'bray', env.dist.method = 'euclidean',
                      spec.select = list(Bacterial_communities = 1:42183,
                                         Fungal_communities = 42184:60783)) %>% 
  mutate(rd = cut(r, breaks = c(-Inf, 0.2, 0.4, Inf),
                  labels = c("< 0.2", "0.2 - 0.4", ">= 0.4")),
         pd = cut(p.value, breaks = c(-Inf, 0.01, 0.05, Inf),
                  labels = c("< 0.01", "0.01 - 0.05", ">= 0.05")))

p2=quickcor(sub_env, type = "upper") +
  geom_square() +
  anno_link(aes(colour = pd, size = rd), data = mantel) +
  scale_size_manual(values = c(0.5, 1, 2)) +
  scale_colour_manual(values = c("#D95F02", "#1B9E77", "#A2A2A288")) +
  guides(size = guide_legend(title = "Mantel's r",
                             override.aes = list(colour = "grey35"), 
                             order = 2),
         colour = guide_legend(title = "Mantel's p", 
                               override.aes = list(size = 3), 
                               order = 1),
         fill = guide_colorbar(title = "Pearson's r", order = 3))

p2

all_plot <- plot_grid(p1,p2,ncol = 1,nrow=2,align ="v")
all_plot

group="mantel test"
width = 240
height =240
ggsave(paste0("",group,".pdf"), all_plot, width = width, height = height,units = "mm")
ggsave(paste0("",group,".JPEG"), all_plot, width = width, height = height,units = "mm")
```





